#!/bin/bash

# make sure errors are not silently ignored
# https://mybinder.readthedocs.io/en/latest/using/config_files.html#config-files
set -ex

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38 --minimize=False
jupyter labextension install @aquirdturtle/collapsible_headings
